# Generated by Django 4.1.3 on 2022-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('grad_year', models.IntegerField()),
                ('n_seats', models.IntegerField()),
                ('body_type', models.CharField(max_length=10)),
                ('engine_cap', models.FloatField()),
            ],
        ),
    ]
