# Generated by Django 4.1.4 on 2022-12-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_brand_carphotomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
