# Generated by Django 4.1.4 on 2022-12-07 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,15}$', 'only letters min 3 max 15')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^0[56789]\\d{8}', 'invalid phone number')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,15}$', 'only letters min 3 max 15')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('/^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\s])[^\\s]{8,20}$', ['password must contain one number (0-9)', 'password must contain one uppercase letter', 'password must contain one lowercase letter', 'password must contain one non-alpha numeric', 'password min 8 max 20 chars'])]),
        ),
    ]
