# Generated by Django 4.1.4 on 2022-12-07 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profilemodel_name_alter_profilemodel_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='avatars'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\s])[^\\s]{8,20}$', ['password must contain one number (0-9)', 'password must contain one uppercase letter', 'password must contain one lowercase letter', 'password must contain one non-alpha numeric', 'password min 8 max 20 chars'])]),
        ),
    ]
